/* ═══════════════════════════════════════════════════════════════
   Skills Seed Taxonomy — ~80 skills for financial services / IM
   ═══════════════════════════════════════════════════════════════ */

import type { Skill } from "../../../types/skills";

export const SEED_SKILLS: Skill[] = [
  // ── TECHNICAL (30 skills) ──────────────────────────────────
  { id: "sk-fin-modeling", name: "Financial Modeling", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-excel-modeling", "sk-cashflow", "sk-cap-structure"], aliases: ["Financial analysis modeling"], version: "1.0.0" },
  { id: "sk-excel-modeling", name: "Excel Modeling", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-fin-modeling", "sk-spreadsheet-auto", "sk-macro"], aliases: ["Spreadsheet modeling"], version: "1.0.0" },
  { id: "sk-sql", name: "SQL", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-python", "sk-data-viz", "sk-data-eng"], aliases: ["Structured Query Language", "Database querying"], version: "1.0.0" },
  { id: "sk-python", name: "Python Programming", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-sql", "sk-data-viz", "sk-ml-basics"], aliases: ["Python scripting", "Python development"], version: "1.0.0" },
  { id: "sk-data-viz", name: "Data Visualization", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-sql", "sk-python", "sk-reporting"], aliases: ["Dashboard design", "Visual analytics"], version: "1.0.0" },
  { id: "sk-cap-structure", name: "Capital Structure Analysis", category: "technical", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-fin-modeling", "sk-credit-analysis", "sk-valuation"], aliases: ["Cap structure"], version: "1.0.0" },
  { id: "sk-cashflow", name: "Cash Flow Modeling", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-fin-modeling", "sk-credit-analysis", "sk-valuation"], aliases: ["DCF modeling", "Cash flow analysis"], version: "1.0.0" },
  { id: "sk-credit-analysis", name: "Credit Analysis", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-fin-modeling", "sk-cap-structure", "sk-underwriting"], aliases: ["Credit assessment", "Credit risk analysis"], version: "1.0.0" },
  { id: "sk-valuation", name: "Valuation", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-fin-modeling", "sk-cashflow", "sk-cap-structure"], aliases: ["Company valuation", "Enterprise valuation"], version: "1.0.0" },
  { id: "sk-underwriting", name: "Underwriting", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-credit-analysis", "sk-risk-assessment", "sk-due-diligence"], aliases: ["Loan underwriting", "Deal underwriting"], version: "1.0.0" },
  { id: "sk-risk-assessment", name: "Risk Assessment", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-credit-analysis", "sk-underwriting", "sk-portfolio-mgmt"], aliases: ["Risk evaluation"], version: "1.0.0" },
  { id: "sk-portfolio-mgmt", name: "Portfolio Management", category: "technical", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-risk-assessment", "sk-valuation", "sk-asset-alloc"], aliases: ["Portfolio construction"], version: "1.0.0" },
  { id: "sk-asset-alloc", name: "Asset Allocation", category: "technical", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-portfolio-mgmt", "sk-risk-assessment"], aliases: ["Strategic allocation"], version: "1.0.0" },
  { id: "sk-reporting", name: "Financial Reporting", category: "technical", aiImpact: "substitutable", lifecycle: "active", adjacentSkillIds: ["sk-data-viz", "sk-excel-modeling", "sk-regulatory-report"], aliases: ["Management reporting", "Investor reporting"], version: "1.0.0" },
  { id: "sk-regulatory-report", name: "Regulatory Reporting", category: "technical", aiImpact: "substitutable", lifecycle: "active", adjacentSkillIds: ["sk-reporting", "sk-compliance"], aliases: ["Regulatory filings"], version: "1.0.0" },
  { id: "sk-compliance", name: "Compliance Monitoring", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-regulatory-report", "sk-legal-doc"], aliases: ["Regulatory compliance"], version: "1.0.0" },
  { id: "sk-due-diligence", name: "Due Diligence", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-credit-analysis", "sk-underwriting", "sk-legal-doc"], aliases: ["DD process", "Deal diligence"], version: "1.0.0" },
  { id: "sk-legal-doc", name: "Legal Documentation Review", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-due-diligence", "sk-compliance"], aliases: ["Contract review", "Legal analysis"], version: "1.0.0" },
  { id: "sk-ai-prompt", name: "AI Prompt Engineering", category: "technical", aiImpact: "emerging", lifecycle: "emerging", adjacentSkillIds: ["sk-ai-eval", "sk-ai-workflow", "sk-python"], aliases: ["Prompt iteration", "LLM prompting"], version: "1.0.0" },
  { id: "sk-ai-eval", name: "AI Output Evaluation", category: "technical", aiImpact: "emerging", lifecycle: "emerging", adjacentSkillIds: ["sk-ai-prompt", "sk-ai-workflow"], aliases: ["LLM output review", "AI quality assessment"], version: "1.0.0" },
  { id: "sk-ai-workflow", name: "AI Workflow Orchestration", category: "technical", aiImpact: "emerging", lifecycle: "emerging", adjacentSkillIds: ["sk-ai-prompt", "sk-ai-eval", "sk-spreadsheet-auto"], aliases: ["AI agent design", "Automation design"], version: "1.0.0" },
  { id: "sk-spreadsheet-auto", name: "Spreadsheet Automation", category: "technical", aiImpact: "substitutable", lifecycle: "deprecated", adjacentSkillIds: ["sk-excel-modeling", "sk-macro"], aliases: ["VBA automation"], version: "1.0.0", deprecatedReason: "Being replaced by AI-powered automation", deprecatedInFavorOf: "sk-ai-workflow" },
  { id: "sk-macro", name: "Macro Authoring", category: "technical", aiImpact: "substitutable", lifecycle: "deprecated", adjacentSkillIds: ["sk-spreadsheet-auto", "sk-excel-modeling"], aliases: ["VBA macros", "Excel macros"], version: "1.0.0", deprecatedReason: "AI can generate and maintain macros", deprecatedInFavorOf: "sk-ai-prompt" },
  { id: "sk-manual-data", name: "Manual Data Extraction", category: "technical", aiImpact: "substitutable", lifecycle: "obsolete", adjacentSkillIds: ["sk-reporting"], aliases: ["Data entry", "Manual data collection"], version: "1.0.0", deprecatedReason: "Fully automatable by AI" },
  { id: "sk-data-eng", name: "Data Engineering", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-sql", "sk-python", "sk-data-viz"], aliases: ["Data pipeline design", "ETL"], version: "1.0.0" },
  { id: "sk-ml-basics", name: "Machine Learning Fundamentals", category: "technical", aiImpact: "emerging", lifecycle: "emerging", adjacentSkillIds: ["sk-python", "sk-data-eng", "sk-ai-eval"], aliases: ["ML basics", "Applied ML"], version: "1.0.0" },
  { id: "sk-deal-structuring", name: "Deal Structuring", category: "technical", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-cap-structure", "sk-underwriting", "sk-negotiation"], aliases: ["Transaction structuring"], version: "1.0.0" },
  { id: "sk-covenant-analysis", name: "Covenant Analysis", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-credit-analysis", "sk-legal-doc", "sk-underwriting"], aliases: ["Covenant monitoring"], version: "1.0.0" },
  { id: "sk-ops-process", name: "Operations Process Design", category: "technical", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-data-eng", "sk-compliance"], aliases: ["Process improvement", "Ops design"], version: "1.0.0" },
  { id: "sk-cybersec-basics", name: "Cybersecurity Awareness", category: "technical", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-compliance"], aliases: ["InfoSec awareness"], version: "1.0.0" },

  // ── BEHAVIORAL (25 skills) ─────────────────────────────────
  { id: "sk-stakeholder-mgmt", name: "Stakeholder Management", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-influence", "sk-written-comm", "sk-presentation"], aliases: ["Stakeholder engagement"], version: "1.0.0" },
  { id: "sk-synthesis", name: "Synthesis & Narrative", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-written-comm", "sk-judgment", "sk-presentation"], aliases: ["Narrative building", "Information synthesis"], version: "1.0.0" },
  { id: "sk-judgment", name: "Judgment Under Uncertainty", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-synthesis", "sk-decision-making", "sk-risk-tolerance"], aliases: ["Decision-making under ambiguity"], version: "1.0.0" },
  { id: "sk-written-comm", name: "Written Communication", category: "behavioral", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-synthesis", "sk-presentation", "sk-stakeholder-mgmt"], aliases: ["Business writing", "Memo writing"], version: "1.0.0" },
  { id: "sk-influence", name: "Influence Without Authority", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-stakeholder-mgmt", "sk-negotiation", "sk-presentation"], aliases: ["Lateral influence", "Cross-functional influence"], version: "1.0.0" },
  { id: "sk-presentation", name: "Presentation & Public Speaking", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-synthesis", "sk-stakeholder-mgmt", "sk-written-comm"], aliases: ["Presenting", "Public speaking"], version: "1.0.0" },
  { id: "sk-negotiation", name: "Negotiation", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-influence", "sk-deal-structuring", "sk-stakeholder-mgmt"], aliases: ["Deal negotiation", "Contract negotiation"], version: "1.0.0" },
  { id: "sk-team-leadership", name: "Team Leadership", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-coaching", "sk-delegation", "sk-stakeholder-mgmt"], aliases: ["People management", "Team management"], version: "1.0.0" },
  { id: "sk-coaching", name: "Coaching & Mentoring", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-team-leadership", "sk-feedback"], aliases: ["Employee development", "Mentoring"], version: "1.0.0" },
  { id: "sk-delegation", name: "Delegation", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-team-leadership", "sk-prioritization"], aliases: ["Task delegation"], version: "1.0.0" },
  { id: "sk-feedback", name: "Giving & Receiving Feedback", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-coaching", "sk-written-comm"], aliases: ["Performance feedback"], version: "1.0.0" },
  { id: "sk-decision-making", name: "Decision-Making Frameworks", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-judgment", "sk-prioritization", "sk-synthesis"], aliases: ["Structured decision-making"], version: "1.0.0" },
  { id: "sk-prioritization", name: "Prioritization", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-decision-making", "sk-delegation"], aliases: ["Time management", "Task prioritization"], version: "1.0.0" },
  { id: "sk-risk-tolerance", name: "Risk Tolerance Calibration", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-judgment", "sk-decision-making"], aliases: ["Risk appetite", "Risk comfort"], version: "1.0.0" },
  { id: "sk-cross-func", name: "Cross-Functional Collaboration", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-stakeholder-mgmt", "sk-influence"], aliases: ["Cross-team collaboration"], version: "1.0.0" },
  { id: "sk-adaptability", name: "Adaptability", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-learning-agility", "sk-resilience"], aliases: ["Change agility", "Flexibility"], version: "1.0.0" },
  { id: "sk-learning-agility", name: "Learning Agility", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-adaptability", "sk-curiosity"], aliases: ["Fast learning", "Continuous learning"], version: "1.0.0" },
  { id: "sk-curiosity", name: "Intellectual Curiosity", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-learning-agility", "sk-synthesis"], aliases: ["Curiosity", "Growth mindset"], version: "1.0.0" },
  { id: "sk-resilience", name: "Resilience", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-adaptability"], aliases: ["Persistence", "Grit"], version: "1.0.0" },
  { id: "sk-ethical-judgment", name: "Ethical Judgment", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-judgment", "sk-compliance"], aliases: ["Ethical reasoning", "Integrity"], version: "1.0.0" },
  { id: "sk-client-relationship", name: "Client Relationship Management", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-stakeholder-mgmt", "sk-negotiation", "sk-influence"], aliases: ["CRM", "Client engagement"], version: "1.0.0" },
  { id: "sk-ai-human-collab", name: "AI-Human Collaboration", category: "behavioral", aiImpact: "emerging", lifecycle: "emerging", adjacentSkillIds: ["sk-ai-prompt", "sk-ai-eval", "sk-adaptability"], aliases: ["Human-AI teaming", "AI collaboration"], version: "1.0.0" },
  { id: "sk-critical-thinking", name: "Critical Thinking", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-synthesis", "sk-judgment", "sk-decision-making"], aliases: ["Analytical thinking"], version: "1.0.0" },
  { id: "sk-conflict-resolution", name: "Conflict Resolution", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-negotiation", "sk-influence", "sk-coaching"], aliases: ["Dispute resolution"], version: "1.0.0" },
  { id: "sk-creative-problem", name: "Creative Problem-Solving", category: "behavioral", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-critical-thinking", "sk-synthesis", "sk-curiosity"], aliases: ["Innovation", "Creative thinking"], version: "1.0.0" },

  // ── DOMAIN (25 skills) ─────────────────────────────────────
  { id: "sk-direct-lending", name: "Direct Lending", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-credit-analysis", "sk-underwriting", "sk-abf"], aliases: ["Private credit lending", "Senior secured lending"], version: "1.0.0" },
  { id: "sk-abf", name: "Asset-Based Finance", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-direct-lending", "sk-credit-analysis", "sk-deal-structuring"], aliases: ["ABF", "Asset-backed lending"], version: "1.0.0" },
  { id: "sk-public-credit", name: "Public Credit Markets", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-credit-analysis", "sk-portfolio-mgmt", "sk-clo-mech"], aliases: ["Liquid credit", "High yield"], version: "1.0.0" },
  { id: "sk-private-equity", name: "Private Equity", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-valuation", "sk-deal-structuring", "sk-cap-structure"], aliases: ["PE", "Buyout"], version: "1.0.0" },
  { id: "sk-clo-mech", name: "CLO Mechanics", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-public-credit", "sk-portfolio-mgmt", "sk-credit-analysis"], aliases: ["Collateralized loan obligations", "CLO structuring"], version: "1.0.0" },
  { id: "sk-restructuring", name: "Restructuring", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-credit-analysis", "sk-legal-doc", "sk-negotiation"], aliases: ["Distressed debt", "Workouts"], version: "1.0.0" },
  { id: "sk-esg", name: "ESG Analysis", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-risk-assessment", "sk-compliance", "sk-reporting"], aliases: ["Sustainability analysis", "ESG scoring"], version: "1.0.0" },
  { id: "sk-insurance", name: "Insurance Solutions", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-risk-assessment", "sk-abf", "sk-deal-structuring"], aliases: ["Insurance-linked strategies", "ILS"], version: "1.0.0" },
  { id: "sk-real-estate", name: "Real Estate Finance", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-valuation", "sk-deal-structuring", "sk-underwriting"], aliases: ["RE lending", "CRE finance"], version: "1.0.0" },
  { id: "sk-fund-ops", name: "Fund Operations", category: "domain", aiImpact: "substitutable", lifecycle: "active", adjacentSkillIds: ["sk-reporting", "sk-compliance", "sk-ops-process"], aliases: ["Fund admin", "Fund accounting"], version: "1.0.0" },
  { id: "sk-investor-relations", name: "Investor Relations", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-client-relationship", "sk-reporting", "sk-presentation"], aliases: ["IR", "LP relations"], version: "1.0.0" },
  { id: "sk-fund-structuring", name: "Fund Structuring", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-fund-ops", "sk-legal-doc", "sk-compliance"], aliases: ["Vehicle structuring", "Fund formation"], version: "1.0.0" },
  { id: "sk-macro-econ", name: "Macroeconomic Analysis", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-portfolio-mgmt", "sk-asset-alloc", "sk-risk-assessment"], aliases: ["Macro research", "Economic analysis"], version: "1.0.0" },
  { id: "sk-sector-research", name: "Sector Research", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-credit-analysis", "sk-valuation", "sk-public-credit"], aliases: ["Industry analysis", "Sector expertise"], version: "1.0.0" },
  { id: "sk-trade-execution", name: "Trade Execution", category: "domain", aiImpact: "substitutable", lifecycle: "active", adjacentSkillIds: ["sk-portfolio-mgmt", "sk-public-credit"], aliases: ["Order execution", "Trading"], version: "1.0.0" },
  { id: "sk-counterparty-mgmt", name: "Counterparty Management", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-risk-assessment", "sk-client-relationship", "sk-compliance"], aliases: ["Counterparty risk"], version: "1.0.0" },
  { id: "sk-tax-structuring", name: "Tax Structuring", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-fund-structuring", "sk-legal-doc", "sk-compliance"], aliases: ["Tax optimization", "Tax planning"], version: "1.0.0" },
  { id: "sk-infra-lending", name: "Infrastructure Lending", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-direct-lending", "sk-deal-structuring", "sk-real-estate"], aliases: ["Infra finance", "Project finance"], version: "1.0.0" },
  { id: "sk-specialty-finance", name: "Specialty Finance", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-abf", "sk-direct-lending", "sk-deal-structuring"], aliases: ["Niche lending", "Specialty credit"], version: "1.0.0" },
  { id: "sk-capital-markets", name: "Capital Markets", category: "domain", aiImpact: "augmentable", lifecycle: "active", adjacentSkillIds: ["sk-public-credit", "sk-trade-execution", "sk-portfolio-mgmt"], aliases: ["Capital markets operations"], version: "1.0.0" },
  { id: "sk-alt-data", name: "Alternative Data Analysis", category: "domain", aiImpact: "emerging", lifecycle: "emerging", adjacentSkillIds: ["sk-data-eng", "sk-ml-basics", "sk-sector-research"], aliases: ["Alt data", "Non-traditional data sources"], version: "1.0.0" },
  { id: "sk-digital-assets", name: "Digital Assets & Blockchain", category: "domain", aiImpact: "emerging", lifecycle: "emerging", adjacentSkillIds: ["sk-capital-markets", "sk-portfolio-mgmt"], aliases: ["Crypto", "DeFi", "Blockchain finance"], version: "1.0.0" },
  { id: "sk-private-wealth", name: "Private Wealth Management", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-client-relationship", "sk-portfolio-mgmt", "sk-asset-alloc"], aliases: ["Wealth advisory", "HNW management"], version: "1.0.0" },
  { id: "sk-venture-credit", name: "Venture Credit", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-direct-lending", "sk-private-equity", "sk-deal-structuring"], aliases: ["Venture lending", "Growth lending"], version: "1.0.0" },
  { id: "sk-secondaries", name: "Secondaries", category: "domain", aiImpact: "resistant", lifecycle: "active", adjacentSkillIds: ["sk-private-equity", "sk-fund-structuring", "sk-valuation"], aliases: ["Secondary markets", "LP secondaries"], version: "1.0.0" },
];

// Quick-lookup map
export const SKILL_MAP = new Map(SEED_SKILLS.map(s => [s.id, s]));

// Keyword patterns for rules-based derivation
export const SKILL_KEYWORDS: Record<string, string[]> = {
  "sk-fin-modeling": ["financial model", "build model", "forecast model", "scenario model"],
  "sk-excel-modeling": ["excel", "spreadsheet", "workbook", "pivot table"],
  "sk-sql": ["sql", "query", "database", "data extract"],
  "sk-python": ["python", "script", "automate", "programming", "code"],
  "sk-data-viz": ["dashboard", "visualization", "chart", "tableau", "power bi"],
  "sk-cap-structure": ["capital structure", "leverage", "debt structure", "equity structure"],
  "sk-cashflow": ["cash flow", "dcf", "discounted", "free cash flow"],
  "sk-credit-analysis": ["credit", "credit risk", "creditworthiness", "default risk"],
  "sk-valuation": ["valuation", "enterprise value", "multiple", "comps", "comparable"],
  "sk-underwriting": ["underwrite", "underwriting", "loan approval", "credit approval"],
  "sk-risk-assessment": ["risk assess", "risk evaluat", "risk analy", "risk factor"],
  "sk-portfolio-mgmt": ["portfolio", "portfolio construct", "rebalance", "allocation"],
  "sk-reporting": ["report", "management report", "investor report", "board report"],
  "sk-regulatory-report": ["regulatory", "filing", "sec ", "compliance report"],
  "sk-compliance": ["compliance", "regulatory", "audit", "controls"],
  "sk-due-diligence": ["due diligence", "diligence", " dd "],
  "sk-legal-doc": ["legal", "contract", "document review", "agreement", "covenant"],
  "sk-ai-prompt": ["prompt", "ai prompt", "llm", "generative ai"],
  "sk-ai-eval": ["ai output", "ai review", "evaluate ai", "verify ai", "check ai"],
  "sk-ai-workflow": ["ai workflow", "automat", "ai tool", "orchestrat"],
  "sk-deal-structuring": ["deal structure", "transaction structure", "structure deal"],
  "sk-covenant-analysis": ["covenant", "covenant comply", "covenant monitor"],
  "sk-stakeholder-mgmt": ["stakeholder", "manage relationship", "communicate with"],
  "sk-synthesis": ["synthesize", "narrative", "summarize", "distill", "memo"],
  "sk-judgment": ["judgment", "ambiguity", "uncertainty", "complex decision"],
  "sk-written-comm": ["write", "draft", "memo", "email", "communicate in writing"],
  "sk-negotiation": ["negotiate", "negotiation", "term sheet", "terms"],
  "sk-presentation": ["present", "presentation", "pitch", "board meeting"],
  "sk-direct-lending": ["direct lend", "private credit", "senior secured"],
  "sk-abf": ["asset-based", "asset based", "abf", "asset-backed"],
  "sk-public-credit": ["public credit", "liquid credit", "high yield", "leveraged loan"],
  "sk-private-equity": ["private equity", "buyout", "lbo", "pe "],
  "sk-clo-mech": ["clo", "collateralized loan", "securitiz"],
  "sk-restructuring": ["restructur", "distressed", "workout", "chapter 11"],
  "sk-esg": ["esg", "sustainability", "environmental", "social governance"],
  "sk-insurance": ["insurance", "ils", "insurance-linked"],
  "sk-real-estate": ["real estate", "property", "cre ", "commercial real estate"],
  "sk-fund-ops": ["fund operation", "fund admin", "nav ", "fund accounting"],
  "sk-investor-relations": ["investor relation", " ir ", "lp relation", "fundrais"],
  "sk-macro-econ": ["macro", "economic", "gdp", "interest rate", "fed "],
  "sk-sector-research": ["sector", "industry research", "industry analy"],
};
