/**
 * Meridian Financial — fictional 6,200-person financial services firm.
 * Static data for the tutorial. No API calls needed.
 */

export const MERIDIAN = {
  name: "Meridian Financial",
  industry: "Financial Services",
  employees: 6200,
  laborCost: 2100000000,
  readiness: { overall: 52, data: 58, talent: 44, governance: 38, culture: 61, technology: 67 },
  functions: [
    { name: "Operations", headcount: 1800, ai_impact: 8.2, readiness: 4.1, color: "var(--amber)" },
    { name: "Technology", headcount: 1200, ai_impact: 6.8, readiness: 7.4, color: "var(--amber)" },
    { name: "Risk & Compliance", headcount: 820, ai_impact: 7.1, readiness: 3.8, color: "var(--coral)" },
    { name: "Finance", headcount: 680, ai_impact: 7.9, readiness: 4.6, color: "var(--amber)" },
    { name: "Wealth Management", headcount: 920, ai_impact: 5.2, readiness: 5.9, color: "var(--dusk)" },
    { name: "HR & People", headcount: 380, ai_impact: 6.4, readiness: 6.1, color: "var(--sage)" },
    { name: "Legal", headcount: 240, ai_impact: 5.8, readiness: 3.2, color: "var(--coral)" },
    { name: "Executive", headcount: 160, ai_impact: 3.1, readiness: 7.8, color: "var(--dusk)" },
  ],
  roles: [
    { title: "Operations Analyst", headcount: 420, ai_impact: 9.1, tasks: 18, automate: 12, augment: 4, keep: 2, function: "Operations" },
    { title: "Loan Processor", headcount: 380, ai_impact: 8.8, tasks: 14, automate: 10, augment: 3, keep: 1, function: "Operations" },
    { title: "Compliance Officer", headcount: 290, ai_impact: 7.2, tasks: 22, automate: 8, augment: 9, keep: 5, function: "Risk & Compliance" },
    { title: "Financial Analyst", headcount: 260, ai_impact: 7.8, tasks: 20, automate: 9, augment: 8, keep: 3, function: "Finance" },
    { title: "Relationship Manager", headcount: 310, ai_impact: 4.8, tasks: 16, automate: 3, augment: 8, keep: 5, function: "Wealth Management" },
    { title: "Risk Analyst", headcount: 240, ai_impact: 7.4, tasks: 19, automate: 8, augment: 7, keep: 4, function: "Risk & Compliance" },
    { title: "Software Engineer", headcount: 480, ai_impact: 6.1, tasks: 24, automate: 6, augment: 12, keep: 6, function: "Technology" },
    { title: "Data Scientist", headcount: 180, ai_impact: 5.4, tasks: 21, automate: 4, augment: 11, keep: 6, function: "Technology" },
    { title: "HR Business Partner", headcount: 140, ai_impact: 6.2, tasks: 17, automate: 6, augment: 7, keep: 4, function: "HR & People" },
    { title: "Legal Counsel", headcount: 120, ai_impact: 5.6, tasks: 26, automate: 5, augment: 12, keep: 9, function: "Legal" },
  ],
  opsAnalystTasks: [
    { name: "Transaction reconciliation", classification: "automate" },
    { name: "Data entry from forms", classification: "automate" },
    { name: "Report generation", classification: "automate" },
    { name: "KYC document processing", classification: "automate" },
    { name: "Payment processing", classification: "automate" },
    { name: "Compliance checklist execution", classification: "automate" },
    { name: "Data validation & cleansing", classification: "automate" },
    { name: "Account setup processing", classification: "automate" },
    { name: "Fee calculation", classification: "automate" },
    { name: "Regulatory filing preparation", classification: "automate" },
    { name: "Exception handling & triage", classification: "automate" },
    { name: "Batch processing oversight", classification: "automate" },
    { name: "Process improvement analysis", classification: "augment" },
    { name: "Stakeholder communication", classification: "augment" },
    { name: "Cross-team coordination", classification: "augment" },
    { name: "Training & knowledge transfer", classification: "augment" },
    { name: "Escalation management", classification: "keep" },
    { name: "Client relationship decisions", classification: "keep" },
  ],
  skillsGaps: [
    { skill: "AI/ML Literacy", severity: "critical", affected_roles: 24, employees: 2100 },
    { skill: "Data Analysis", severity: "high", affected_roles: 18, employees: 1600 },
    { skill: "Process Automation", severity: "high", affected_roles: 15, employees: 1200 },
    { skill: "Change Management", severity: "high", affected_roles: 12, employees: 980 },
    { skill: "Prompt Engineering", severity: "medium", affected_roles: 20, employees: 1800 },
    { skill: "Data Governance", severity: "medium", affected_roles: 9, employees: 720 },
  ],
  scenario: { headcount_delta: -180, cost_savings_pct: 12, timeline_months: 18, reskilling_investment: 4200000, attrition_pct: 3.2 },
  keyTension: "Operations has the highest automation potential (8.2/10) but the lowest readiness (4.1/10) — the biggest opportunity is also the biggest risk.",
  surpriseInsight: "Wealth Management, often assumed safe from AI disruption, has 40% of roles flagged for significant augmentation within 18 months.",
} as const;
